In [144]:
import pandas as pd
data = pd.read_csv('data.csv',sep=';',engine='python',encoding='UTF8')

In [145]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        32 non-null     int64
 1   Duration  32 non-null     int64
 2   Date      31 non-null     object
 3   Pulse     32 non-null     int64
 4   Maxpulse  32 non-null     int64
 5   Calories  30 non-null     object
dtypes: int64(4), object(2)
memory usage: 1.6+ KB

In [146]:
data.head(3)

   ID  Duration          Date  Pulse  Maxpulse Calories
0   0        60  '2020/12/01'    110       130     4091
1   1        60  '2020/12/02'    117       145     4790
2   2        60  '2020/12/03'    103       135     3400

In [ ]:
data.tail(3)

In [147]:
data2 = pd.DataFrame(data)

In [148]:
data2['Calories'].fillna(0, inplace = True)
data2

    ID  Duration          Date  Pulse  Maxpulse Calories
0    0        60  '2020/12/01'    110       130     4091
1    1        60  '2020/12/02'    117       145     4790
2    2        60  '2020/12/03'    103       135     3400
3    3        45  '2020/12/04'    109       175     2824
4    4        45  '2020/12/05'    117       148     4060
5    5        60  '2020/12/06'    102       127     3000
6    6        60  '2020/12/07'    110       136     3740
7    7       450  '2020/12/08'    104       134     2533
8    8        30  '2020/12/09'    109       133     1951
9    9        60  '2020/12/10'     98       124     2690
10  10        60  '2020/12/11'    103       147     3293
11  11        60  '2020/12/12'    100       120     2507
12  12        60  '2020/12/12'    100       120     2507
13  13        60  '2020/12/13'    106       128     3453
14  14        60  '2020/12/14'    104       132     3793
15  15        60  '2020/12/15'     98       123     2750
16  16        60  '2020/12/16'     98       120     2152
17  17        60  '2020/12/17'    100       120     3000
18  18        45  '2020/12/18'     90       112        0
19  19        60  '2020/12/19'    103       123     3230
20  20        45  '2020/12/20'     97       125   2430 2
21   1        60  '2020/12/21'    108       131     3642
22  22        45           NaN    100       119     2820
23  23        60  '2020/12/23'    130       101     3000
24  24        45  '2020/12/24'    105       132     2460
25  25        60  '2020/12/25'    102       126     3345
26  26        60      20201226    100       120     2500
27  27        60  '2020/12/27'     92       118     2410
28  28        60  '2020/12/28'    103       132        0
29  29        60  '2020/12/29'    100       132     2800
30  30        60  '2020/12/30'    102       129     3803
31  31        60  '2020/12/31'     92       115     2430

In [149]:
data2['Date'].fillna('1900/01/01', inplace = True)
data2

    ID  Duration          Date  Pulse  Maxpulse Calories
0    0        60  '2020/12/01'    110       130     4091
1    1        60  '2020/12/02'    117       145     4790
2    2        60  '2020/12/03'    103       135     3400
3    3        45  '2020/12/04'    109       175     2824
4    4        45  '2020/12/05'    117       148     4060
5    5        60  '2020/12/06'    102       127     3000
6    6        60  '2020/12/07'    110       136     3740
7    7       450  '2020/12/08'    104       134     2533
8    8        30  '2020/12/09'    109       133     1951
9    9        60  '2020/12/10'     98       124     2690
10  10        60  '2020/12/11'    103       147     3293
11  11        60  '2020/12/12'    100       120     2507
12  12        60  '2020/12/12'    100       120     2507
13  13        60  '2020/12/13'    106       128     3453
14  14        60  '2020/12/14'    104       132     3793
15  15        60  '2020/12/15'     98       123     2750
16  16        60  '2020/12/16'     98       120     2152
17  17        60  '2020/12/17'    100       120     3000
18  18        45  '2020/12/18'     90       112        0
19  19        60  '2020/12/19'    103       123     3230
20  20        45  '2020/12/20'     97       125   2430 2
21   1        60  '2020/12/21'    108       131     3642
22  22        45    1900/01/01    100       119     2820
23  23        60  '2020/12/23'    130       101     3000
24  24        45  '2020/12/24'    105       132     2460
25  25        60  '2020/12/25'    102       126     3345
26  26        60      20201226    100       120     2500
27  27        60  '2020/12/27'     92       118     2410
28  28        60  '2020/12/28'    103       132        0
29  29        60  '2020/12/29'    100       132     2800
30  30        60  '2020/12/30'    102       129     3803
31  31        60  '2020/12/31'     92       115     2430

A Partir deste ponto, foi necessário simular os erros solicitados no enúnciado, tendo em vista que ao atualizar o compilador do python e a kernel do Jupyter Notebook os erros descritos não ocorrem, então foi feita a correção e/ou forçado para que eles aconteçam;

In [150]:
data2.replace('1900/01/01','NaN', inplace = True)
data2

    ID  Duration          Date  Pulse  Maxpulse Calories
0    0        60  '2020/12/01'    110       130     4091
1    1        60  '2020/12/02'    117       145     4790
2    2        60  '2020/12/03'    103       135     3400
3    3        45  '2020/12/04'    109       175     2824
4    4        45  '2020/12/05'    117       148     4060
5    5        60  '2020/12/06'    102       127     3000
6    6        60  '2020/12/07'    110       136     3740
7    7       450  '2020/12/08'    104       134     2533
8    8        30  '2020/12/09'    109       133     1951
9    9        60  '2020/12/10'     98       124     2690
10  10        60  '2020/12/11'    103       147     3293
11  11        60  '2020/12/12'    100       120     2507
12  12        60  '2020/12/12'    100       120     2507
13  13        60  '2020/12/13'    106       128     3453
14  14        60  '2020/12/14'    104       132     3793
15  15        60  '2020/12/15'     98       123     2750
16  16        60  '2020/12/16'     98       120     2152
17  17        60  '2020/12/17'    100       120     3000
18  18        45  '2020/12/18'     90       112        0
19  19        60  '2020/12/19'    103       123     3230
20  20        45  '2020/12/20'     97       125   2430 2
21   1        60  '2020/12/21'    108       131     3642
22  22        45           NaN    100       119     2820
23  23        60  '2020/12/23'    130       101     3000
24  24        45  '2020/12/24'    105       132     2460
25  25        60  '2020/12/25'    102       126     3345
26  26        60      20201226    100       120     2500
27  27        60  '2020/12/27'     92       118     2410
28  28        60  '2020/12/28'    103       132        0
29  29        60  '2020/12/29'    100       132     2800
30  30        60  '2020/12/30'    102       129     3803
31  31        60  '2020/12/31'     92       115     2430

In [151]:
data2.replace({'Date' : {
    '20201226' : "'2020/12/26'"
}}, inplace = True)
data2

    ID  Duration          Date  Pulse  Maxpulse Calories
0    0        60  '2020/12/01'    110       130     4091
1    1        60  '2020/12/02'    117       145     4790
2    2        60  '2020/12/03'    103       135     3400
3    3        45  '2020/12/04'    109       175     2824
4    4        45  '2020/12/05'    117       148     4060
5    5        60  '2020/12/06'    102       127     3000
6    6        60  '2020/12/07'    110       136     3740
7    7       450  '2020/12/08'    104       134     2533
8    8        30  '2020/12/09'    109       133     1951
9    9        60  '2020/12/10'     98       124     2690
10  10        60  '2020/12/11'    103       147     3293
11  11        60  '2020/12/12'    100       120     2507
12  12        60  '2020/12/12'    100       120     2507
13  13        60  '2020/12/13'    106       128     3453
14  14        60  '2020/12/14'    104       132     3793
15  15        60  '2020/12/15'     98       123     2750
16  16        60  '2020/12/16'     98       120     2152
17  17        60  '2020/12/17'    100       120     3000
18  18        45  '2020/12/18'     90       112        0
19  19        60  '2020/12/19'    103       123     3230
20  20        45  '2020/12/20'     97       125   2430 2
21   1        60  '2020/12/21'    108       131     3642
22  22        45           NaN    100       119     2820
23  23        60  '2020/12/23'    130       101     3000
24  24        45  '2020/12/24'    105       132     2460
25  25        60  '2020/12/25'    102       126     3345
26  26        60  '2020/12/26'    100       120     2500
27  27        60  '2020/12/27'     92       118     2410
28  28        60  '2020/12/28'    103       132        0
29  29        60  '2020/12/29'    100       132     2800
30  30        60  '2020/12/30'    102       129     3803
31  31        60  '2020/12/31'     92       115     2430

In [152]:
data2['Date'] = pd.to_datetime(data2['Date'])
data2

    ID  Duration       Date  Pulse  Maxpulse Calories
0    0        60 2020-12-01    110       130     4091
1    1        60 2020-12-02    117       145     4790
2    2        60 2020-12-03    103       135     3400
3    3        45 2020-12-04    109       175     2824
4    4        45 2020-12-05    117       148     4060
5    5        60 2020-12-06    102       127     3000
6    6        60 2020-12-07    110       136     3740
7    7       450 2020-12-08    104       134     2533
8    8        30 2020-12-09    109       133     1951
9    9        60 2020-12-10     98       124     2690
10  10        60 2020-12-11    103       147     3293
11  11        60 2020-12-12    100       120     2507
12  12        60 2020-12-12    100       120     2507
13  13        60 2020-12-13    106       128     3453
14  14        60 2020-12-14    104       132     3793
15  15        60 2020-12-15     98       123     2750
16  16        60 2020-12-16     98       120     2152
17  17        60 2020-12-17    100       120     3000
18  18        45 2020-12-18     90       112        0
19  19        60 2020-12-19    103       123     3230
20  20        45 2020-12-20     97       125   2430 2
21   1        60 2020-12-21    108       131     3642
22  22        45        NaT    100       119     2820
23  23        60 2020-12-23    130       101     3000
24  24        45 2020-12-24    105       132     2460
25  25        60 2020-12-25    102       126     3345
26  26        60 2020-12-26    100       120     2500
27  27        60 2020-12-27     92       118     2410
28  28        60 2020-12-28    103       132        0
29  29        60 2020-12-29    100       132     2800
30  30        60 2020-12-30    102       129     3803
31  31        60 2020-12-31     92       115     2430

In [158]:
data2 = data2.dropna()
data2

    ID  Duration       Date  Pulse  Maxpulse Calories
0    0        60 2020-12-01    110       130     4091
1    1        60 2020-12-02    117       145     4790
2    2        60 2020-12-03    103       135     3400
3    3        45 2020-12-04    109       175     2824
4    4        45 2020-12-05    117       148     4060
5    5        60 2020-12-06    102       127     3000
6    6        60 2020-12-07    110       136     3740
7    7       450 2020-12-08    104       134     2533
8    8        30 2020-12-09    109       133     1951
9    9        60 2020-12-10     98       124     2690
10  10        60 2020-12-11    103       147     3293
11  11        60 2020-12-12    100       120     2507
12  12        60 2020-12-12    100       120     2507
13  13        60 2020-12-13    106       128     3453
14  14        60 2020-12-14    104       132     3793
15  15        60 2020-12-15     98       123     2750
16  16        60 2020-12-16     98       120     2152
17  17        60 2020-12-17    100       120     3000
18  18        45 2020-12-18     90       112        0
19  19        60 2020-12-19    103       123     3230
20  20        45 2020-12-20     97       125   2430 2
21   1        60 2020-12-21    108       131     3642
23  23        60 2020-12-23    130       101     3000
24  24        45 2020-12-24    105       132     2460
25  25        60 2020-12-25    102       126     3345
26  26        60 2020-12-26    100       120     2500
27  27        60 2020-12-27     92       118     2410
28  28        60 2020-12-28    103       132        0
29  29        60 2020-12-29    100       132     2800
30  30        60 2020-12-30    102       129     3803
31  31        60 2020-12-31     92       115     2430